# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05fe57a8a24a2d75ceaaaacb2f02d7cf42676d9cff6f5824f0c7ad5620469934c51a29e193f583529c78e680e96ea53882fa52a8513dcce8e0f966c18bde8e79

test:
  secret_key_base: fef9bb94c80b294d5a99f99183619e4a1a80ddee85740d551400f15ced8f7389288ccf237cead47220452f27ccbb73d8394af5a7c0c341651bec63644c128b66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
